customType: cmd
customConfig:
  getCurrentStateCommand: cat custom-state.json
  getChangesCommand: echo ""
  createCommand: cat custom-state.json
  updateCommand: cat custom-state.json
  deleteCommand: echo ok
