regions: eu-north-1
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
customType: cmd
customConfig:
  getCurrentStateCommand: cat {{ var.currentState }}-state.json
  getChangesCommand: cat {{ var.changesState }}-changes.json
  createCommand: cat {{ var.commandState }}-state.json
  updateCommand: cat {{ var.commandState }}-state.json
  deleteCommand: echo ok
