regions: eu-north-1
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
customType: cmd
customConfig:
  getCurrentStateCommand: cat {{ var.aCurrentState }}-state.json
  getChangesCommand: cat changes.json
  createCommand: cat {{ var.aCommandState }}-state.json
  updateCommand: cat {{ var.aCommandState }}-state.json
  deleteCommand: echo ok
