regions: eu-west-1
commandRole: arn:aws:iam::{{ var.ACCOUNT_1_ID }}:role/OrganizationAccountAccessRole
customType: cmd
customConfig:
  getCurrentStateCommand: cat {{ var.bCurrentState }}-state.json
  getChangesCommand: cat changes.json
  createCommand: cat {{ var.bCommandState }}-state.json
  updateCommand: cat {{ var.bCommandState }}-state.json
  deleteCommand: echo ok
depends: /a.yml
