#
# Test AI services opt-out policies
#

tagPolicies: true

aiServicesOptOutPolicies:
  MyTestOptOut:
    description: Just for testing

organizationalUnits:
  Root:
    accounts:
      - id: "{{ env.TKM_ORG_A_MASTER_ACCOUNT_ID }}"
        description: master
        status: disabled
  Root/test-accounts:
    bootstrapConfigSets:
      - bootstrap
    configSets:
      - basic
    accounts:
      - id: "{{ env.TKM_ORG_A_ACCOUNT_1_ID }}"
        vars:
          vpcCidr: 10.0.0.0/24
          costCenter: aaa
      - id: "{{ env.TKM_ORG_A_ACCOUNT_2_ID }}"
        vars:
          vpcCidr: 10.0.1.0/24
          costCenter: bbb
      - id: "{{ env.TKM_ORG_A_ACCOUNT_3_ID }}"
        vars:
          vpcCidr: 10.0.2.0/24
          costCenter: ccc
  "Root/sandbox accounts/sandbox-1": {}
  "Root/sandbox accounts/sandbox-2":
    aiServicesOptOutPolicies: MyTestOptOut
    accounts:
      - "{{ env.TKM_ORG_A_ACCOUNT_4_ID }}"
      - "{{ env.TKM_ORG_A_ACCOUNT_5_ID }}"
